### ISSUE TITLE
'n' doesn't work

### ISSUE THREAD

**Issue by dirkk0** [doersino/markdeep-slides#22]
'n' doesn't work in the demo.
The error on the console is:
ncaught ReferenceError: theme is not defined
    at togglePresenterNotes (markdeep-slides.js:497)
    at HTMLBodyElement.keyPress (markdeep-slides.js:

Chrome or Firefox, MacOSX

**Comment by doersino** [comment]
Fixed – this was due to a recent options processing overhaul. Sorry!

**Comment by dirkk0** [comment]
no problem - while you are at it: there is always a horizontal scrollbar at the bottom; it seems the screen is always a tad too big. should I open a new issue?

**Comment by doersino** [comment]
That's be great!
