### ISSUE TITLE
Fix incorrect slide dimensions when "old-style" scroll bars are enabled

### ISSUE THREAD

**Issue by doersino** [doersino/markdeep-slides#23]
*As mentioned by @dirkk0 in #22.*

Turns out that when scroll bars are set to always be visible and thus take up space (or the user is on an OS that always shows scroll bars), the slides aren't sized properly. This is bad because:

* In draft mode, a horizontal scroll bar is visible because the slides continue horizontally just a bit behind the vertical scroll bar.
* In presentation mode, a vertical scroll bar is visible. I'm not yet sure why exactly this is.

I didn't notice this during development because I'm using macOS on a laptop, where scroll bars are overlaid onto the content *only* when scrolling and don't interfere with the viewport.

I'll try to address this soon.

**Comment by dirkk0** [comment]
thx!!

**Comment by doersino** [comment]
Fixed – better late than never. This took some work (& testing) because I was relying on the `vw` and `vh` CSS units for sizing, and they include the scroll bars, which is objectively dumb (I cannot come up with any advantages of this definition, anyway).

So instead, I'm now using JS to compute the "proper" `vw` and `vh` values, as variables `--vw` and `--wh`, on

* load and
* window resizing and
* fullscreen change,

and use those variables wherever I was previously using the built-in units, which feels *so wrong* but appears to work. (This convoluted approach is necessary because scroll bars are not the same width across all platforms.)

Thanks again for bringing this to my attention!
