### ISSUE TITLE
Options for a progress bar location

### ISSUE THREAD

**Issue by mindv0rtex** [doersino/markdeep-slides#24]
It is a feature request to consider. I would like to have the progress bar be directly below the slide title. If you look at the Metropolis theme for Beamer, they have options to place it at the top of a slide (like it is now), at the bottom, or under the title.

I don't know JS but I could probably take a stab at it if you could perhaps provide me with some pointers...

**Comment by doersino** [comment]
*I got the idea for progress bars from that Beamer theme!* Having them below headings would be neat, but fraught with potential issues:

* Not every slide might have a heading, but I think the progress bar should appear on every slide for visual consistency. Call it opinionated software. 😉
* A slide might contain multiple headings – showing the progress bar twice would look awkward, showing it only below the first heading might clash with the heading hierarchy.
* Which levels of headings should the progress bar be displayed below? Level 1, level 2, both, or more? (Sure, this could be configurable, but that'd add complexity.)
* Themes may style headings however they want, which can make a progress bar below them look awkward in some cases – see the included `serif` theme for an example.
* It's trickier to implement – I'd have to write code to traverse the document, looking for headings and modifying them. Currently, the progress bar is simply added to each slide during the process of splitting the document into slides.

So this is something I sadly won't be working on – in my mind, it's too much added complexity for too little benefit. Sorry about that!

---

If you'd prefer the progress bar at the bottom, that's easy (this snippet is adapted from the included `deepsea` theme):

```css
.slide-progress {
    --progress-height: 0.2rem;
    margin-top: calc(var(--slide-height) - var(--progress-height)) !important;
    height: var(--progress-height);
}
```

**Comment by mindv0rtex** [comment]
Thanks @doersino. Actually, I already relied on the ability of not even having a slide title in my presentation so your points are well taken. But I do appreciate the code snippet for the bottom placement!
