### ISSUE TITLE
Parsing of code in slides, HTML entities

### ISSUE THREAD

**Issue by bkmgit** [doersino/markdeep-slides#27]
There can be errors when parsing HTML entities in slides, in particular `<`, `>` and `&` may be parsed incorrectly if not replaced by `&lt;`, `&gt;` and `&amp;` or `&#60;`, `&#62;` and `&#38;`. As an example

```C
for(int i=0;i<10;i++){
  printf("%i\n",i);
}
```
will render incorrectly in slides, but
```C
for(int i=0;i&lt;10;i++){
  printf("%i\n",i);
}
```
will render correctly.

**Comment by doersino** [comment]
Right – sadly, that's a limitation of Markdeep; or rather, of processing a loaded HTML file as text inside a browser. As you've noticed, using HTML entities is one way of working around this behavior.

There's more details about this in the [Markdeep documentation](https://casual-effects.com/markdeep/features.md.html#basicformatting/codeblocks/less-thansignsincode):

![Screen Shot 2021-12-05 at 09 24 57](https://user-images.githubusercontent.com/1944410/144739259-63d101fb-d82a-4a4a-a62c-932b324e4fc6.png)

**Comment by bkmgit** [comment]
May be helpful to have this demonstrated/mentioned in the demo presentation.

**Comment by doersino** [comment]
True – thanks for the pull request adding this information, I'll merge it in a minute!
