### ISSUE TITLE
fixed width font custom iosevka

### ISSUE THREAD

**Issue by IngmarBitter** [doersino/markdeep-slides#30]
you are using my favorite font family for fixed width font contexts such as code snippets. Great!
I have spent a lot of time tweaking the iosevka font to have well-distinguishable l1ij, O0, {([ and a few others. I have attached the result with this issue ticket. Feel free to review it and, if you like, to replace the current default iosevka with my custom edition. I grant BSD style totally free use of these fonts with no requirement to mention where they are from. Just use it and be happy :-)

[iosevka-Ingmar-narrow.zip](https://github.com/doersino/markdeep-slides/files/9985997/iosevka-Ingmar-narrow.zip)

**Comment by doersino** [comment]
Thank you! Locally, I'm also running a modified version of Iosevka for my text editing and terminal hacking needs, but I think keeping the default makes the most sense here – the great thing about Iosevka is that anyone can substitute their own/preferred version just as you have done.
